import pandas as pd
import numpy as np
import scipy.stats as stats
from sklearn.model_selection import train_test_split
import os

DATA_PATH = "data/diabetic_data.csv"
REPORT_PATH = "app/templates/validation_report.html"

def check_integrity(df):
    html = "<h2>Data Integrity Check</h2>"
    html += f"<p>Total Rows: {len(df)}</p>"
    
    # Nulls
    nulls = df.isnull().sum()
    nulls = nulls[nulls > 0]
    if not nulls.empty:
        html += "<h3>Missing Values</h3><ul>"
        for col, count in nulls.items():
            html += f"<li>{col}: {count} ({count/len(df)*100:.2f}%)</li>"
        html += "</ul>"
    else:
        html += "<p>No missing values found (after initial load).</p>"
        
    return html

def check_drift(df):
    html = "<h2>Data Drift Analysis</h2><p>Comparing Train (80%) vs Test (20%) Splits</p>"
    
    # Simple Drift Check on Numeric Columns
    # Stripping out non-numeric
    numeric_df = df.select_dtypes(include=[np.number])
    
    if numeric_df.empty:
        return html + "<p>No numeric columns to check for drift.</p>"
        
    train, test = train_test_split(numeric_df, test_size=0.2, random_state=42)
    
    html += "<table border='1' style='border-collapse: collapse; width: 100%;'><tr><th>Column</th><th>KS Statistic</th><th>P-Value</th><th>Drift Detected?</th></tr>"
    
    drift_detected = False
    for col in numeric_df.columns:
        stat, p_val = stats.ks_2samp(train[col], test[col])
        is_drift = p_val < 0.05
        if is_drift: drift_detected = True
        
        color = "#ffcccc" if is_drift else "#ccffcc"
        html += f"<tr style='background-color: {color}'><td>{col}</td><td>{stat:.4f}</td><td>{p_val:.4f}</td><td>{'YES' if is_drift else 'NO'}</td></tr>"
        
    html += "</table>"
    
    if not drift_detected:
        html += "<p style='color: green; font-weight: bold;'>No significant drift detected in numeric features.</p>"
    else:
        html += "<p style='color: red; font-weight: bold;'>Drift detected in some features!</p>"
        
    return html

def generate_report():
    print("Loading data...")
    df = pd.read_csv(DATA_PATH, na_values=['?'])
    
    # Basic Cleaning for realistic check
    drop_cols = ['weight', 'payer_code', 'medical_specialty']
    df = df.drop(columns=[c for c in drop_cols if c in df.columns])
    df = df.dropna(subset=['readmitted'])
    
    html_content = """
    <html>
    <head>
        <title>Data Validation Report</title>
        <style>
            body { font-family: sans-serif; padding: 20px; max-width: 800px; margin: 0 auto; }
            h2 { border-bottom: 2px solid #ccc; padding-bottom: 5px; }
            table { margin-top: 10px; }
            td, th { padding: 8px; text-align: left; }
        </style>
    </head>
    <body>
        <h1>Data Validation & Drift Report</h1>
        <p>Generated by Custom Validation Pipeline</p>
    """
    
    html_content += check_integrity(df)
    html_content += check_drift(df)
    
    html_content += "</body></html>"
    
    with open(REPORT_PATH, "w") as f:
        f.write(html_content)
        
    print(f"Report saved to {REPORT_PATH}")

if __name__ == "__main__":
    generate_report()
